### ISSUE TITLE
Problems with Mac

### ISSUE THREAD

**Issue by JesusLopTem** [mstuyts/QuickCRS#1]
Impossible to install on Mac: The plugin is broken. Python says: **int() arguyment must be a string or a number, not "QPyNullVariant"**
Qgis 2.18.2 on MacOS 10.11.6

**Comment by mstuyts** [comment]
Can you post the full error message, so I can figure out where the problem can be found. Since I don't have a Mac, it's hard to solve.

**Comment by JesusLopTem** [comment]
Sorry, this is the information I get when trying to install the plugin, nothing else. This is a capture (sorry, some parts are in Spanish)
![captura de pantalla 2017-03-02 a las 14 23 39](https://cloud.githubusercontent.com/assets/19475313/23508876/e54f9d06-ff53-11e6-8293-56e5e71e5a0c.png)
.

**Comment by mstuyts** [comment]
I released a new version on the QGIS plugin repository. Could you give it a try?

**Comment by JesusLopTem** [comment]
0.3.3 is the last version? If yes, the problem to install remains, same error. Thanks for your interest.

**Comment by mstuyts** [comment]
Version 0.3.3 was my first attempt to solve the problem. I made another attempt to solve it. Can you try to install version 0.3.4?

**Comment by JesusLopTem** [comment]
All ok in this new version. No problem with installation and 0.3.4 works well on mac. Great job! Thanks a lot.
